name: OS X binary
on: [push]
jobs:
  macos:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install brew dependencies
        run: brew install cmake libsndfile curl m4
      - name: Build dependencies
        run: cd external/tinc; ./build_deps.sh; cd -
      - name: Build and Test
        run: ./run.sh
#        env:
#          DEVELOPER_DIR: /Applications/Xcode_11.4.app/Contents/Developer